openapi: 3.0.0

info:
  version: 1.0.0
  title: API de Produtos
  termsOfService: http://localhost:8080/docs/terms.html # Add em 'resources/static/docs/terms.html'
  contact:
    name: Pegasus SA
    email: suporte@pegasus.com.br
    url: http://localhost:8080/pegasus/website.html # Add em 'resources/static/pegasus/website.html'
  license:
      name: Licença MIT
      url: http://localhost:8080/docs/license.html # Add em 'resources/static/docs/license.html'
  description: |
    API de estudo para gerenciamento de produtos.  
    Contém operações de criação, consulta, atualização e exclusão de elementos do tipo produto.

tags:
  - name: product
    description: Operações CRUD de Produto

servers:
  - url: http://localhost:8080/products
    description: Servidor local para solicitações de produtos

paths:
  /products:
    parameters:
      - $ref: '#/components/parameters/_header_x_pegasus_client_id'
    get:
      tags: [product]
      operationId: products-get-page
      summary: Listar produtos
      description: Retorna uma lista paginada de produtos.
      parameters:
        - $ref: '#/components/parameters/_query_offset'
        - $ref: '#/components/parameters/_query_limit'
      responses:
        '200':
          description: Página solicitada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductPageResponseType'
        "400":
          $ref: '#/components/responses/bad-request-response'
        "500":
          $ref: '#/components/responses/internal-server-error-response'

    post:
      tags: [product]
      operationId: products-create
      summary: Criar produto
      description: Cria um novo produto com os dados fornecidos.
      requestBody:
        description: Dados de criação
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreateRequest'
      responses:
        '201':
          description: Elemento criado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        "400":
          $ref: '#/components/responses/bad-request-response'
        "500":
          $ref: '#/components/responses/internal-server-error-response'

  /products/{id}:
    parameters:
      - $ref: '#/components/parameters/_header_x_pegasus_client_id'
      - $ref: '#/components/parameters/_path_product_id'
    get:
      tags: [product]
      operationId: products-get-one
      summary: Buscar elemento por ID
      description: Obtem os metadados de um elemento através do identificador
      responses:
        '200':
          description: Elemento encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        "400":
          $ref: '#/components/responses/bad-request-response'
        "404":
          $ref: '#/components/responses/not-found-response'
        "500":
          $ref: '#/components/responses/internal-server-error-response'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorResponseType'
    put:
      tags: [product]
      operationId: products-update
      summary: Atualizar produto
      description: Atualiza os metadados de um elemento através do identificador
      requestBody:
        description: Os dados da atualização do elemento.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductUpdateRequest'
      responses:
        '200':
          description: O elemento atualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
    delete:
      tags: [product]
      operationId: products-delete
      summary: Excluir produto
      responses:
        '204':
          description: Produto excluído

components:
  parameters:
    _path_product_id:
      name: id
      in: path
      required: true
      description: ID do produto
      schema:
        type: integer

    _header_x_pegasus_client_id:
      name: X-PEGASUS-CLIENT-ID
      in: header
      required: true
      description: Client ID header
      schema:
        type: string
      example: a1b30a84-7bf3-442e-84a0-e935d8163b5a
    _query_offset:
      name: _offset
      in: query
      schema:
        type: integer
      required: false
      example: 0
    _query_limit:
      name: _limit
      in: query
      schema:
        type: integer
      required: false
      example: 20

  responses:
    BadRequest:
      description: Requisição inválida
    NotFound:
      description: Recurso não encontrado
    InternalServerError:
      description: Erro interno

    bad-request-response:
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestType'

    not-found-response:
        description: Element not found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotFoundResponseType'

    conflict-response:
        description: Recurso não encontrado
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConflictResponseType'

    internal-server-error-response:
        description: Erro interno no serviço
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InternalServerErrorResponseType'

    default-error-response:
        description: Erro inesperado
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExceptionResponseType'

  schemas:
    # [ TYPE → RESPONSE → FAIL ]
    ExceptionResponseType:
      type: object
      description: Modelo padrão para erros
      properties:
        details:
          type: array
          items:
            type: string
          description: Detalhes do erro ocorrido.
          example: [ "Mensagem de erro 1" ]

    BadRequestType:
      allOf:
        - $ref: '#/components/schemas/ExceptionResponseType'
        - type: object
          example:
            details:
              - "O campo Name é obrigatório"
              - "O campo CharClassId é obrigatório"
              - "O campo CharRaceId é obrigatório"

    NotFoundResponseType:
      allOf:
        - $ref: '#/components/schemas/ExceptionResponseType'
        - type: object
          example:
            details:
              - "Character 123 não encontrado"

    ConflictResponseType:
      allOf:
        - $ref: '#/components/schemas/ExceptionResponseType'
        - type: object
          example:
            details:
              - "O Character 123 ja existe."

    InternalServerErrorResponseType:
      allOf:
        - $ref: '#/components/schemas/ExceptionResponseType'
        - type: object
          example:
            details:
              - "Banco de dados off-line"

    Product:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        identifier:
          type: string
        quantity:
          type: integer
        description:
          type: string
        price:
          type: number
          format: float
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ProductCreateRequest:
      type: object
      required: [name, identifier, quantity]
      properties:
        name:
          type: string
        identifier:
          type: string
        quantity:
          type: integer
        description:
          type: string
        price:
          type: number

    ProductUpdateRequest:
      allOf:
        - $ref: '#/components/schemas/ProductCreateRequest'

    ProductResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Product'

    ProductPageResponseType:
      type: object
      properties:
        pagination:
          type: object
          properties:
            page: { type: integer }
            size: { type: integer }
            totalPages: { type: integer }
            totalElements: { type: integer }
        data:
          type: array
          items:
            $ref: '#/components/schemas/Product'

