<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.4</version>
        <relativePath/>
    </parent>

    <name>pegasus-api-restful</name>
    <description>API RESTful gerada com OpenAPI Generator</description>
    <packaging>jar</packaging>

    <groupId>br.com.pegasus.api.restful</groupId>
    <artifactId>pegasus-api-restful</artifactId>
    <version>1.0.0</version>

    <properties>
        <java.version>17</java.version>
        <path.resources>${project.basedir}/src/main/resources</path.resources>
        <path.root>${project.build.directory}</path.root>
        <path.openapi>${path.resources}/openapi</path.openapi>

        <!-- OPENAPI -->
        <openapi.inputSpec>${path.openapi}/openapi.yaml</openapi.inputSpec>
        <openapi.apiPackage>br.com.pegasus.gen.openapi.api</openapi.apiPackage>
        <openapi.modPackage>br.com.pegasus.gen.openapi.type</openapi.modPackage>
        <openapi.tempDirect>${path.openapi}</openapi.tempDirect>

        <!-- GENERATE CLASS -->
        <gen.from>src/main/template/restful</gen.from>
        <gen.import.restful>br/com/pegasus/gen/restful/**/*.java</gen.import.restful>
        <gen.to>${path.root}/generated-sources/local-project/src/main/java</gen.to>

    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- OpenApi -->
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.8.9</version>
        </dependency>
        <dependency>  <!-- Remove vulnerabilidade do 'springdoc-openapi-starter-webmvc-ui' -->
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.18.0</version>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
            <version>0.2.2</version>
        </dependency>
        <dependency>
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
            <version>2.0.1.Final</version>
        </dependency>
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <version>1.3.2</version>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>3.0.1</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>

            <plugin>
                <!-- Plugin de compilação -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.10.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <id>openapi</id>
                        <configuration>
                            <inputSpec>${openapi.inputSpec}</inputSpec>
                            <apiPackage>${openapi.apiPackage}</apiPackage>
                            <modelPackage>${openapi.modPackage}</modelPackage>
                            <templateDirectory>${openapi.tempDirect}</templateDirectory>
                            <generatorName>spring</generatorName>
                            <configOptions>
                                <interfaceOnly>true</interfaceOnly>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <!-- Importe de pacotes do diretório template [1/2] -->
                <!-- transporta os pacotes desejados para a pasta target -->
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.3.1</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <id>generate-id</id>
                        <configuration>
                            <resources>
                                <resource>
                                    <directory>${gen.from}</directory>
                                    <includes>
                                        <include>${gen.import.restful}</include>
                                    </includes>
                                </resource>
                            </resources>
                            <outputDirectory>${gen.to}</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <!-- Importe de pacotes do diretório template [2/2] -->
                <!-- registra os pacotes importados -->
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.4.0</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <id>generate-id</id>
                        <configuration>
                            <sources>
                                <source>${gen.to}</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>

</project>
